### ISSUE TITLE
SPIKE - how many ways are there to create a function

### ISSUE THREAD

**Issue by alexw1983** [Hoobachube/jacks-app-chest#37]
## Description

Javascript has many ways of creating a function. What are they?

## Questions
1. What are the different ways of creating a function
1. Give examples for each type and how to call those functions.

**Comment by Hoobachube** [comment]
There are four ways a function can be created in JavaScript. They are as follows:

A function as a statement

A function as an expression

A function as an arrow function

A function created using the Function constructor

 

Function Statement

A function statement starts with the function keyword and it must have a name. Its main characteristic is that you can call a function before it has been declared e.g.

Function Add(num1,num2) {

Let sum = 10+ 5;

Return sum;

}

 

Function as an expression

Unlike a function statement, a function expression can be created without a name. In a function expression you assign a function to a variable. This means that you cannot call a function before it has been declared. If you try to it will raise a ReferenceError. Below is an example a function expression;

Let add = function (num1,num2) {

Let sum = 10+ 5;

Return sum;

}

As soon as it has been defined it can be used immediately. This is called Immediately Invoked Function Expression.

 

Arrow function

The main purpose of an Arrow function is to create a shorter syntax to a function expression. It is also used to increase the readability of the code

var add = (num1, num2)=> num1+num2;

let res = add(10,5);

console.log(res);

Arrow functions cannot have arguments or its own this object. It also cannot be used as a constructor. 

 

Function constructor

In the function constructor you pass the parameters and the function body as a string. Function constructors are always created as global. They are generally not used as they can cause performance issues. Example below;

Var add = Function(‘num1’ , ’num2’ , ‘return num1+num2’);

Let res = add (10,5);

Console.log(res);

**Comment by alexw1983** [comment]
> 
> As soon as it has been defined it can be used immediately. This is called Immediately Invoked Function Expression.
> 

Please give an example of an Immediately Invoked Function Expression. Note these are often called IIFE (pronounced iffy)

**Comment by Hoobachube** [comment]
To expand on IIFE;

(function() {
var a= 3;
Console.log(a);
})();
The outer parenthesis will make the function an expression and the last two make it an immediately invoked function expression.  In this situation the console will return the value 3. If however;

var a = 2;

(function() {
var a= 3;
Console.log(a);
})();

Console.log(a);

This would firstly return the value of 3 and then 2.  This is because the IIFE is immediately invoked.  The second console.log(a) can’t access anything within the IIFE as it is now closed so it will use the original defined variable var a = 2; and will return the value of 2.
A primarily used because, as shown, cannot be used in the global scope.  This is useful to stop conflictions in code and for security purposes.

**Comment by alexw1983** [comment]
Please write a working rpogram that takes in
